repos:

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        exclude: ^docs/

-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    -   id: black
        exclude: ^docs/

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        exclude: ^docs/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        exclude: ^docs/
