[tool.poetry]
name = "log_decor"
description = "Logging decorators for classes and methods."
authors = [
    "Bernardo Paulsen <bernardopaulsen@gmail.com>"
]
license = "MIT"

readme = "README.md"

packages = [
    { include = "log_decor" },
]

keywords = ["logging", "decorators", "OOP"]

[tool.poetry.urls]
"Github" = "https://github.com/bernardopaulsen/log_decor"
"Read the Docs" = "https://test.pypi.org/project/log-decor/"

[tool.poetry.build]
generate-setup-file = false

[tool.poetry.dependencies]
python = "^3.10"