[tool.poetry]
name = "log_decor"
version = "1.0.1"
description = "Logging decorators for classes and methods."
authors = ["Bernardo Paulsen <bernardopaulsen@gmail.com>"]
license = "MIT"
readme = "README.rst"
packages = [{ include = "src/log_decor" }]
keywords = ["logging", "decorators", "OOP"]

[tool.poetry.dependencies]
typing_extensions = "*"

[tool.poetry.urls]
"Github" = "https://github.com/bernardopaulsen/log_decor"
"Read the Docs" = "https://log-decor.readthedocs.io"