name: "Run Unit Tests"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Run unit tests
        run: coverage run -m unittest discover -s tests/

      - name: Generate coverage report
        run: coverage html

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: htmlcov/
