name: "Run Unit Tests"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install unittest-xml-reporting

      - name: Run unit tests
        run: python -m xmlrunner -o test-reports

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: test-reports/
