name: "Run Unit Tests"

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install unittest-xml-reporting

      - name: Run unit tests
        run: python -m xmlrunner -o test-results

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        with:
          files: |
            test-results/**.xml
